[package]
name = "rs-es-dashview"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.136"
tokio = { version = "1.43.0", features = ["full"] }
warp = "0.3.7"
